// <auto-generated />
using System;
using AutomobileRentals_EntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AutomobileRentals_EntityFramework.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240429094643_firstDbDesign")]
    partial class firstDbDesign
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AutomobileRentals_EntityFramework.Models.booking", b =>
                {
                    b.Property<int>("bok_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bok_id"));

                    b.Property<DateTime>("Bok_enddate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("bok_isconfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("bok_ref_person")
                        .HasColumnType("int");

                    b.Property<int>("bok_ref_vehicle")
                        .HasColumnType("int");

                    b.Property<DateTime>("bok_startdate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("bok_totalprice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("bok_id")
                        .HasName("pk_booking");

                    b.HasIndex(new[] { "bok_ref_person" }, "ix_bok_ref_person");

                    b.HasIndex(new[] { "bok_ref_vehicle" }, "ix_bok_ref_vehicle");

                    b.ToTable("Bookings", (string)null);
                });

            modelBuilder.Entity("AutomobileRentals_EntityFramework.Models.person", b =>
                {
                    b.Property<int>("per_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("per_id"));

                    b.Property<string>("per_email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_idno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_passwordhash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("per_username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("per_id");

                    b.ToTable("People", (string)null);
                });

            modelBuilder.Entity("AutomobileRentals_EntityFramework.Models.vehicle", b =>
                {
                    b.Property<int>("veh_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("veh_id"));

                    b.Property<bool>("is_available")
                        .HasColumnType("bit");

                    b.Property<string>("veh_brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("veh_model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("veh_priceperday")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("veh_year")
                        .HasColumnType("int");

                    b.HasKey("veh_id")
                        .HasName("pk_vehicle");

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("AutomobileRentals_EntityFramework.Models.booking", b =>
                {
                    b.HasOne("AutomobileRentals_EntityFramework.Models.person", "bok_ref_personNavigation")
                        .WithMany("personBookings")
                        .HasForeignKey("bok_ref_person")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutomobileRentals_EntityFramework.Models.vehicle", "bok_ref_vehicleNavigation")
                        .WithMany("vehicleBookings")
                        .HasForeignKey("bok_ref_vehicle")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("bok_ref_personNavigation");

                    b.Navigation("bok_ref_vehicleNavigation");
                });

            modelBuilder.Entity("AutomobileRentals_EntityFramework.Models.person", b =>
                {
                    b.Navigation("personBookings");
                });

            modelBuilder.Entity("AutomobileRentals_EntityFramework.Models.vehicle", b =>
                {
                    b.Navigation("vehicleBookings");
                });
#pragma warning restore 612, 618
        }
    }
}
